# Generated by Django 3.2 on 2021-04-06 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 12, 1, 15, 380422)),
        ),
    ]
