# Generated by Django 3.2 on 2021-04-06 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_image_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 12, 20, 5, 155077)),
        ),
    ]
